#!/usr/bin/env tsx
/**
 * Contract checker: schemas.py (Python) vs types.ts (TypeScript).
 *
 * Reads:
 *   - schemas.json  — generated by export-schemas.py
 *   - scripts/contract-naming-map.json — maps PythonName → TypeScriptName
 *   - nomos-console/src/lib/types.ts   — parsed via ts-morph
 *
 * Checks:
 *   - All Python fields exist in the TypeScript interface
 *   - All TypeScript fields exist in the Python schema
 *   - Basic type compatibility (string, number/integer, boolean, array)
 *
 * Exit 0 — all aligned.
 * Exit 1 — one or more mismatches found.
 */

import { Project, InterfaceDeclaration, PropertySignature, SyntaxKind } from "ts-morph";
import * as fs from "fs";
import * as path from "path";

// ─── Types ────────────────────────────────────────────────────────────────────

interface JsonSchema {
  properties?: Record<string, JsonSchemaProperty>;
  required?: string[];
  [key: string]: unknown;
}

interface JsonSchemaProperty {
  type?: string;
  anyOf?: Array<{ type?: string; format?: string }>;
  items?: { type?: string };
  format?: string;
  default?: unknown;
  [key: string]: unknown;
}

interface NamingMap {
  [pythonName: string]: string;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Resolve the primary JSON Schema type for a property.
 * Handles anyOf (union/nullable) by collecting all non-null types.
 */
function resolvePythonType(prop: JsonSchemaProperty): string[] {
  if (prop.anyOf) {
    return prop.anyOf
      .map((v) => v.type)
      .filter((t): t is string => !!t && t !== "null");
  }
  if (prop.type) return [prop.type];
  return ["unknown"];
}

/**
 * Determine whether a TypeScript property node is nullable (T | null).
 */
function isTsNullable(prop: PropertySignature): boolean {
  const typeNode = prop.getTypeNode();
  if (!typeNode) return false;
  const text = typeNode.getText();
  return text.includes("| null") || text.includes("null |");
}

/**
 * Get the primary TS type keyword(s) for a property (ignores null/undefined).
 */
function resolveTsType(prop: PropertySignature): string[] {
  const typeNode = prop.getTypeNode();
  if (!typeNode) return ["unknown"];

  const text = typeNode.getText();

  // Union type — split and filter nulls
  if (typeNode.getKind() === SyntaxKind.UnionType) {
    return text
      .split("|")
      .map((t) => t.trim())
      .filter((t) => t !== "null" && t !== "undefined")
      .map((t) => simplifyTsType(t));
  }

  return [simplifyTsType(text)];
}

function simplifyTsType(t: string): string {
  if (t.startsWith("'") || t.startsWith('"')) return "string"; // string literal
  if (t.endsWith("[]")) return "array";
  if (t.startsWith("Array<")) return "array";
  if (t === "Record<string, unknown>" || t === "Record<string, any>") return "object";
  return t;
}

/**
 * Map a Python JSON Schema type to the corresponding TypeScript type name(s).
 */
function pythonToTsType(pyTypes: string[]): string[] {
  return pyTypes.flatMap((pt) => {
    switch (pt) {
      case "string":
        return ["string"];
      case "integer":
        return ["number"];
      case "number":
        return ["number"];
      case "boolean":
        return ["boolean"];
      case "array":
        return ["array"];
      case "object":
        return ["object", "Record<string, unknown>"];
      default:
        return [pt];
    }
  });
}

// ─── Main ─────────────────────────────────────────────────────────────────────

function main(): void {
  const root = path.resolve(__dirname, "..");
  const schemasPath = path.join(root, "schemas.json");
  const namingMapPath = path.join(root, "scripts", "contract-naming-map.json");
  const typesPath = path.join(root, "nomos-console", "src", "lib", "types.ts");

  // Load schemas.json
  if (!fs.existsSync(schemasPath)) {
    console.error("ERROR: schemas.json not found — run: python scripts/export-schemas.py > schemas.json");
    process.exit(1);
  }
  const allSchemas: Record<string, JsonSchema> = JSON.parse(fs.readFileSync(schemasPath, "utf-8"));

  // Load naming map
  const namingMap: NamingMap = JSON.parse(fs.readFileSync(namingMapPath, "utf-8"));

  // Parse TypeScript types with ts-morph
  const project = new Project({ addFilesFromTsConfig: false });
  const sourceFile = project.addSourceFileAtPath(typesPath);

  // Build a map of interface name → InterfaceDeclaration
  const tsInterfaces = new Map<string, InterfaceDeclaration>();
  for (const iface of sourceFile.getInterfaces()) {
    tsInterfaces.set(iface.getName(), iface);
  }

  console.log("=== Contract Check: schemas.py vs types.ts ===\n");
  console.log(`Python schemas: ${Object.keys(allSchemas).length}`);
  console.log(`TypeScript interfaces: ${tsInterfaces.size}`);
  console.log(`Naming map entries: ${Object.keys(namingMap).length}\n`);

  let totalChecked = 0;
  let totalMismatches = 0;
  const mismatches: string[] = [];

  for (const [pythonName, tsName] of Object.entries(namingMap)) {
    const schema = allSchemas[pythonName];
    if (!schema) {
      const msg = `SKIP  ${pythonName} → ${tsName}: Python schema not found in schemas.json`;
      console.log(msg);
      continue;
    }

    const tsIface = tsInterfaces.get(tsName);
    if (!tsIface) {
      const msg = `FAIL  ${pythonName} → ${tsName}: TypeScript interface '${tsName}' not found in types.ts`;
      console.error(msg);
      mismatches.push(msg);
      totalMismatches++;
      continue;
    }

    const pythonProps = schema.properties ?? {};
    const pythonRequired = new Set(schema.required ?? []);

    // Build TS property map
    const tsProps = new Map<string, PropertySignature>();
    for (const p of tsIface.getProperties()) {
      tsProps.set(p.getName(), p);
    }

    let schemaMismatches = 0;

    // Check Python → TypeScript
    for (const [fieldName, pyProp] of Object.entries(pythonProps)) {
      if (!tsProps.has(fieldName)) {
        const msg = `  FIELD_MISSING  ${pythonName}.${fieldName} not in TypeScript '${tsName}'`;
        console.error(msg);
        mismatches.push(`${pythonName} → ${tsName}: ${msg.trim()}`);
        schemaMismatches++;
        continue;
      }

      // Type compatibility check
      const pyTypes = resolvePythonType(pyProp);
      const expectedTsTypes = pythonToTsType(pyTypes);
      const tsProp = tsProps.get(fieldName)!;
      const actualTsTypes = resolveTsType(tsProp);

      const compatible = expectedTsTypes.some((expected) =>
        actualTsTypes.some((actual) => actual === expected || actual.startsWith(expected))
      );

      if (!compatible) {
        const msg = `  TYPE_MISMATCH  ${pythonName}.${fieldName}: Python=${pyTypes.join("|")} expected TS=${expectedTsTypes.join("|")} but got TS=${actualTsTypes.join("|")}`;
        console.error(msg);
        mismatches.push(`${pythonName} → ${tsName}: ${msg.trim()}`);
        schemaMismatches++;
      }
    }

    // Check TypeScript → Python (extra fields in TS not in Python)
    for (const [tsFieldName] of tsProps) {
      if (!(tsFieldName in pythonProps)) {
        const msg = `  EXTRA_FIELD    ${tsName}.${tsFieldName} not in Python '${pythonName}'`;
        console.error(msg);
        mismatches.push(`${pythonName} → ${tsName}: ${msg.trim()}`);
        schemaMismatches++;
      }
    }

    if (schemaMismatches === 0) {
      console.log(`OK    ${pythonName} → ${tsName} (${Object.keys(pythonProps).length} fields)`);
    } else {
      console.error(`FAIL  ${pythonName} → ${tsName} (${schemaMismatches} mismatches)`);
      totalMismatches += schemaMismatches;
    }

    totalChecked++;
  }

  console.log("\n=== Summary ===");
  console.log(`Schemas checked: ${totalChecked}`);
  console.log(`Mismatches: ${totalMismatches}`);

  if (mismatches.length > 0) {
    console.error("\nAll mismatches:");
    for (const m of mismatches) {
      console.error(`  - ${m}`);
    }
    console.error("\nContract check FAILED — fix mismatches above.");
    process.exit(1);
  }

  console.log("\nContract check PASSED — schemas.py and types.ts are aligned.");
  process.exit(0);
}

main();
